package libManage;
/**
 * @author Frank Einstein
 * @author Chip
 * 
 * Last updated 2/20
 */
public class CustomerView extends javax.swing.JPanel {

    /**
     * Creates new form CustomerView
     */
    public CustomerView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        custBookSearchLbl = new javax.swing.JLabel();
        custBookSearchTxtField = new javax.swing.JTextField();
        custViewLabel = new javax.swing.JLabel();
        custShowCheckoutsLbl = new javax.swing.JLabel();
        custShowCheckoutsButton = new javax.swing.JButton();
        custSearchDatabaseButton = new javax.swing.JButton();
        custViewExitButton = new javax.swing.JButton();

        custBookSearchLbl.setText("Search book database:");

        custBookSearchTxtField.setText("Book search");
        custBookSearchTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custBookSearchTxtFieldActionPerformed(evt);
            }
        });

        custViewLabel.setText("Customer View");

        custShowCheckoutsLbl.setText("Show checked out books:");

        custShowCheckoutsButton.setText("Show my checked out books");

        custSearchDatabaseButton.setText("Search Database");
        custSearchDatabaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custSearchDatabaseButtonActionPerformed(evt);
            }
        });

        custViewExitButton.setText("Exit Program");
        custViewExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custViewExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(custViewLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(custShowCheckoutsLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(custShowCheckoutsButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(custBookSearchLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(custBookSearchTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(custSearchDatabaseButton)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(custViewExitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(custViewLabel)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custBookSearchLbl)
                    .addComponent(custBookSearchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custSearchDatabaseButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custShowCheckoutsLbl)
                    .addComponent(custShowCheckoutsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(custViewExitButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void custBookSearchTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custBookSearchTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custBookSearchTxtFieldActionPerformed

    private void custSearchDatabaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custSearchDatabaseButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custSearchDatabaseButtonActionPerformed

    private void custViewExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custViewExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_custViewExitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel custBookSearchLbl;
    private javax.swing.JTextField custBookSearchTxtField;
    private javax.swing.JButton custSearchDatabaseButton;
    private javax.swing.JButton custShowCheckoutsButton;
    private javax.swing.JLabel custShowCheckoutsLbl;
    private javax.swing.JButton custViewExitButton;
    private javax.swing.JLabel custViewLabel;
    // End of variables declaration//GEN-END:variables
}
