/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libManage;

import java.io.File;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Frank Einstein
 */
public class librarianLogin extends javax.swing.JFrame {

    /**
     * Creates new form librarianLogin
     */
    public librarianLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        loginLabel = new javax.swing.JLabel();
        librarian_username_label = new javax.swing.JLabel();
        librarian_password_label = new javax.swing.JLabel();
        librarian_username_txtfield = new javax.swing.JTextField();
        librarian_password_txtfield = new javax.swing.JTextField();
        libLoginButton = new javax.swing.JButton();
        libLoginExitButton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginLabel.setText("Librarian Login");

        librarian_username_label.setText("Username");

        librarian_password_label.setText("Password");

        librarian_username_txtfield.setText("Username");

        librarian_password_txtfield.setText("Password");

        libLoginButton.setText("Login");
        libLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libLoginButtonActionPerformed(evt);
            }
        });

        libLoginExitButton.setText("Exit Program");
        libLoginExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libLoginExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(librarian_username_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(librarian_username_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(librarian_password_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(librarian_password_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(loginLabel)))
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(libLoginExitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(libLoginButton)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginLabel)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(librarian_username_label)
                    .addComponent(librarian_username_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(librarian_password_label)
                    .addComponent(librarian_password_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(libLoginButton)
                    .addComponent(libLoginExitButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void libLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libLoginButtonActionPerformed
            
                String username = librarian_username_txtfield.getText();
        String password = librarian_password_txtfield.getText();
                String filePath = "librarians.txt";
        
      verifyLogin(username, password, filePath);

    }//GEN-LAST:event_libLoginButtonActionPerformed

    private void libLoginExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libLoginExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_libLoginExitButtonActionPerformed

    public static void verifyLogin(String username, 
            String password, String filePath) {
            boolean found = false;
        String tempUsername = "";
        String tempPassword = "";
            
        librarianView libView = new librarianView();
        libView.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        librarianLogin libLogin = new librarianLogin();
        libLogin.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        try{
        Scanner reader = new Scanner(System.in);
        
        reader = new Scanner(new File(filePath));
        reader.useDelimiter("[,\n]");
        
        while(reader.hasNext() && !found) {
            tempUsername = reader.next();
            tempPassword = reader.next();
            

            
            if(tempUsername.trim().equals(username) && 
                    tempPassword.trim().equals(password)) {
                found = true;
                JOptionPane.showMessageDialog(null, "Sucessful login");
                
          libLogin.setVisible(false);
        libLogin.dispose();        
        libView.setVisible(true);
      
        
            }
        }
              if(found == false){
                JOptionPane.showMessageDialog(null, "Unsucessful login");
        }
        reader.close();
        }
        catch(Exception e) {

        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(librarianLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(librarianLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(librarianLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(librarianLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new librarianLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton libLoginButton;
    private javax.swing.JButton libLoginExitButton;
    private javax.swing.JLabel librarian_password_label;
    private javax.swing.JTextField librarian_password_txtfield;
    private javax.swing.JLabel librarian_username_label;
    private javax.swing.JTextField librarian_username_txtfield;
    private javax.swing.JLabel loginLabel;
    // End of variables declaration//GEN-END:variables
}
