/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package libManage;

/**
 *
 * @author Frank Einstein
 */
public class librarianView extends javax.swing.JFrame {

    /** Creates new form librarianView */
    public librarianView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        libBookSearchLbl = new javax.swing.JLabel();
        libCustomerSearchLbl = new javax.swing.JLabel();
        libBookSearchTxtFld = new javax.swing.JTextField();
        libCustomerSearchTxtFld = new javax.swing.JTextField();
        libViewLbl = new javax.swing.JLabel();
        libBookSearchButton = new javax.swing.JButton();
        libCustomerSearchButton = new javax.swing.JButton();
        libCreateNewCustomerLbl = new javax.swing.JLabel();
        libCreateNewCustomerTxtFld = new javax.swing.JTextField();
        libCreateNewCustomerButton = new javax.swing.JButton();
        libViewExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        libBookSearchLbl.setText("Book search:");

        libCustomerSearchLbl.setText("Customer search:");

        libBookSearchTxtFld.setText("Book search");

        libCustomerSearchTxtFld.setText("Customer search");
        libCustomerSearchTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libCustomerSearchTxtFldActionPerformed(evt);
            }
        });

        libViewLbl.setText("Librarian View");

        libBookSearchButton.setText("Book Search");
        libBookSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libBookSearchButtonActionPerformed(evt);
            }
        });

        libCustomerSearchButton.setText("Customer Search");
        libCustomerSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libCustomerSearchButtonActionPerformed(evt);
            }
        });

        libCreateNewCustomerLbl.setText("Create new Customer:");

        libCreateNewCustomerTxtFld.setText("Create Customer");

        libCreateNewCustomerButton.setText("Create Customer");

        libViewExitButton.setText("Exit Program");
        libViewExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libViewExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(libCustomerSearchLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(libCustomerSearchTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(libCustomerSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(libCreateNewCustomerLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(libCreateNewCustomerTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(libCreateNewCustomerButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(libViewLbl))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(libBookSearchLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(libBookSearchTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(libBookSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(libViewExitButton)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(libViewLbl)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(libBookSearchLbl)
                    .addComponent(libBookSearchTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(libBookSearchButton))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(libCustomerSearchLbl)
                    .addComponent(libCustomerSearchTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(libCustomerSearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(libCreateNewCustomerLbl)
                    .addComponent(libCreateNewCustomerTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(libCreateNewCustomerButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(libViewExitButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void libCustomerSearchTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libCustomerSearchTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_libCustomerSearchTxtFldActionPerformed

    private void libBookSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libBookSearchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_libBookSearchButtonActionPerformed

    private void libCustomerSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libCustomerSearchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_libCustomerSearchButtonActionPerformed

    private void libViewExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libViewExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_libViewExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(librarianView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(librarianView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(librarianView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(librarianView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new librarianView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton libBookSearchButton;
    private javax.swing.JLabel libBookSearchLbl;
    private javax.swing.JTextField libBookSearchTxtFld;
    private javax.swing.JButton libCreateNewCustomerButton;
    private javax.swing.JLabel libCreateNewCustomerLbl;
    private javax.swing.JTextField libCreateNewCustomerTxtFld;
    private javax.swing.JButton libCustomerSearchButton;
    private javax.swing.JLabel libCustomerSearchLbl;
    private javax.swing.JTextField libCustomerSearchTxtFld;
    private javax.swing.JButton libViewExitButton;
    private javax.swing.JLabel libViewLbl;
    // End of variables declaration//GEN-END:variables

}
